
package Proyecto;

import javax.swing.JOptionPane;


public class splashscreem extends javax.swing.JFrame {

    /**
     * Creates new form splashscreem
     */
    public splashscreem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        BackGroundImage = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGroundPanel.setBackground(new java.awt.Color(255, 204, 204));
        BackGroundPanel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/splash.png"))); // NOI18N
        BackGroundImage.setText("jLabel1");
        BackGroundImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGroundImage.setMaximumSize(new java.awt.Dimension(400, 300));
        BackGroundImage.setMinimumSize(new java.awt.Dimension(400, 300));
        BackGroundPanel.add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 470, 430));

        LoadingBar.setBackground(new java.awt.Color(0, 102, 255));
        LoadingBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 500, 10));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        LoadingLabel.setText("Loading...");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 60)); // NOI18N
        jLabel2.setText("Jhave Jire");
        BackGroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        LoadingValue.setText("0 %");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashscreem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashscreem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashscreem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashscreem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        splashscreem sp = new splashscreem();
        sp.setVisible(true);
        
        
        try{
            for(int i=0;i<=100;i++){
        Thread.sleep(40);
        sp.LoadingValue.setText(i +"%");
        
        if (i>=30 && i<50) {
                sp.LoadingLabel.setText("Cargando...");
            } else if (i>=50 && i<90) {
                sp.LoadingLabel.setText("Cargando Componentes...");
            } else if (i>=90 && i<=100) {
                sp.LoadingLabel.setText("Iniciando Aplicación...");
            }
        sp.LoadingBar.setValue(i);
 
                } 
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        VentanaPrincipalFerreteria ventana = new VentanaPrincipalFerreteria ();  //creamos la ventana        
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
